---
_extends: template

repository:
  name: spec
  description: Tox Protocol Specification
  homepage: https://toktok.ltd/spec
  topics: tox, protocol, toxcore
  has_issues: true

branches:
  - name: "master"
    protection:
      required_status_checks:
        contexts:
          - Codacy/PR Quality Review
          - Travis CI - Pull Request
          - WIP
          - code-review/reviewable
          - license/cla
